version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    working_dir: "/src"
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
